export const filterDataConstants = {
    INIT_FILTER_SECTION: 'INIT_FILTER_SECTION',
    SET_CONTEXTS_LIST_BY_FILTER: 'SET_CONTEXTS_LIST_BY_FILTER',
    SET_CONTEXTS_CHECKS_BY_FILTER: 'SET_CONTEXTS_CHECKS_BY_FILTER',
    SET_DIMENTIONS_LIST_BY_FILTER: 'SET_DIMENTIONS_LIST_BY_FILTER',
    SET_DIMENTIONS_CHECKS_BY_FILTER: 'SET_DIMENTIONS_CHECKS_BY_FILTER',
    SET_FILTERS_LIST_BY_FILTER: 'SET_FILTERS_LIST_BY_FILTER',
    SET_FILTERS_CHECKS_BY_FILTER: 'SET_FILTERS_CHECKS_BY_FILTER',
    SET_SORT_RULES_BY_FILTER: 'SET_SORT_RULES_BY_FILTER',
};