export const filterDataConstants = {
    GET_CONTEXTS_LIST_BY_FILTER: 'GET_CONTEXTS_LIST_BY_FILTER',
    SET_CONTEXTS_LIST_BY_FILTER: 'SET_CONTEXTS_LIST_BY_FILTER',
    GET_DIMENTIONS_LIST_BY_FILTER: 'GET_DIMENTIONS_LIST_BY_FILTER',
    SET_DIMENTIONS_LIST_BY_FILTER: 'SET_DIMENTIONS_LIST_BY_FILTER',
    GET_FILTERS_LIST_BY_FILTER: 'GET_FILTERS_LIST_BY_FILTER',
    SET_FILTERS_LIST_BY_FILTER: 'SET_FILTERS_LIST_BY_FILTER',
};