export const filtersConstants = {
    GET_CONTEXTS_LIST: 'GET_CONTEXTS_LIST',
    CONTEXTS_LIST_REQUESTED: 'CONTEXTS_LIST_REQUESTED',
    CONTEXTS_LIST_SUCCEEDED: 'CONTEXTS_LIST_SUCCEEDED',
};

export const seachFilterConstants = {
    SEARCH_FILTER_COMPARE_FULL: '**',
    SEARCH_FILTER_COMPARE_PARTICAL: '*_',
    SEARCH_FILTER_COMPARE_BEGINNING_FROM: '""',
};

export const orderFilterConstants = {
    ORDER_FILTER_ALPHABETICAL_UP: 'A-Z',
};