export const filtersConstants = {
    CONTEXTS_LIST_REQUESTED: 'CONTEXTS_LIST_REQUESTED',
    CONTEXTS_LIST_SUCCEEDED: 'CONTEXTS_LIST_SUCCEEDED',
    GET_DIMENTIONS_LIST: 'GET_DIMENTIONS_LIST',
    GET_FILTERS_LIST: 'GET_FILTERS_LIST',
};

export const seachFilterConstants = {
    SEARCH_FILTER_COMPARE_FULL: '**',
    SEARCH_FILTER_COMPARE_PARTICAL: '*_',
    SEARCH_FILTER_COMPARE_BEGINNING_FROM: '""',
};

export const orderFilterConstants = {
    ORDER_FILTER_ALPHABETICAL_UP: 'A-Z',
};